name: Golang

on:
  push:
    paths:
      - ".github/workflows/golang.yml"
      - "golang/**"

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: docker/setup-qemu-action@v2 # for multi-architecture builds
      - id: buidlx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./golang/
          file: ./golang/Dockerfile
          # platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/code-golang:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/code-golang:1.19
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          readme-filepath: ./golang/README.md
          short-description: https://github.com/tianze0926/devcontainer
      - run: echo ${{ steps.docker_build.outputs.digest }}